### ISSUE TITLE
Toggle back to 'all threads'?

### ISSUE THREAD

**Issue by vincentsels** [mayerwin/vs-debug-single-thread#1]
Once I switch to follow only the current thread, there seems to be no way to switch back to following any thread - when I click the 'snowflake' button again, it does nothing; which is contra-intuitive since it is a toggle button.

**Comment by mayerwin** [comment]
Can you post a screenshot of what you see in the threads window before your click the button, after you enable it, and when you disable it (back to initial state)? Normally all threads should be unfrozen at the end.
