### ISSUE TITLE
Updating this extension.

### ISSUE THREAD

**Issue by ericmutta** [mayerwin/vs-debug-single-thread#2]
The idea behind this extension is very useful, but the implementation sadly seems very "hit and miss"...sometimes it works, sometimes it doesn't. I was thinking of contributing possible fixes but looking through the files in this repo, I can't seem to find the code for the actual commands. What file are they in?

**Comment by mayerwin** [comment]
Can you clarify what you mean by commands?

**Comment by mayerwin** [comment]
Sorry, the MyCommand file was incorrectly ignored. I have re-added it to the repo. Thanks!

**Comment by ericmutta** [comment]
Thanks for uploading the missing file! I am hoping to see if it's possible to freeze/thaw threads in the same process as the current thread. When doing multiprocess debugging with a desktop server app and an Android client app you essentially get two debuggers running (Visual Studio's native one and Xamarin's debugger) and the Xamarin one doesn't seem to handle freeze/thaw properly. My hope is that I can get the extension to handle just the threads running on the server process.
