### ISSUE TITLE
Can this be updated to support Visual Studio 2022 Release?

### ISSUE THREAD

**Issue by bodzilla** [mayerwin/vs-debug-single-thread#5]

**Comment by SeppPenner** [comment]
I would like to see this as well and would help if someone can tell me what is needed 😄

**Comment by bodzilla** [comment]
> I would like to see this as well and would help if someone can tell me what is needed 😄

Are you saying you are able to adapt the code to work with 2022?

**Comment by SeppPenner** [comment]
> > I would like to see this as well and would help if someone can tell me what is needed 😄
> 
> Are you saying you are able to adapt the code to work with 2022?

I have never before developed a VS extension. Currently, I'm not sure what needs to be changed to get it working in VS2022.
In the best case, just some configuration file needs to be changed.

**Comment by mayerwin** [comment]
I am planning to release a compatible version by the end of the year. Hopefully by then Microsoft will make it possible to upload two VSIX for the same marketplace listing (so it can support both VS 2019 and VS 2022).

**Comment by mayerwin** [comment]
I have just released a version for VS 2022 which can be downloaded here: https://github.com/mayerwin/vs-debug-single-thread/releases/tag/4.0.0
I'll push it to the marketplace when Microsoft will have added the possibility to upload two VSIX for the same listing.

**Comment by bodzilla** [comment]
> I have just released a version for VS 2022 which can be downloaded here: https://github.com/mayerwin/vs-debug-single-thread/releases/tag/4.0.0 I'll push it to the marketplace when Microsoft will have added the possibility to upload two VSIX for the same listing.

Hi, I've justed installed it and tested, doesn't work unfortunately.

**Comment by mayerwin** [comment]
@bodzilla I just tested on my end and it does work. What makes you think it doesn't? Basically, you should see the toolbar if it works, however remember the buttons will be greyed out until a debug session is launched.

**Comment by bodzilla** [comment]
@mayerwin I tested with the toolbar and pressed the "Focus on current thread" button during a Parallel.ForEach procedure and it wasn't focusing on the thread I selected - kept bouncing between all the other threads like it normally does.

I'm running VS 2022 Professional Edition, if that helps.

**Comment by mayerwin** [comment]
@bodzilla Do you see something like this in the Threads window when you press the Focus on current thread button?
![image](https://user-images.githubusercontent.com/2272127/144760371-64db7e3f-fe6b-4968-9e35-c1b00d09f1c8.png)

That's all the extension does (pausing the threads as you'd do yourself in the Threads window).

**Comment by bodzilla** [comment]
@mayerwin Ahh yes it does, my apologies - I didn't realise my code was doing some async work within the same thread which freed it to do other work. Works as expected.

**Comment by SeppPenner** [comment]
Nice work :) As far as I have tested it, it works.

**Comment by qwertie** [comment]
Something that might confuse people is that the 2022 version is not mentioned on [the VS marketplace](https://marketplace.visualstudio.com/items?itemName=mayerwin.DebugSingleThread).
