### ISSUE TITLE
Feature Request: Modify CTRL +T + key bindings as it is the Visual Studio default binding for Code Search

### ISSUE THREAD

**Issue by gpshonik** [mayerwin/vs-debug-single-thread#8]
Would it be possible to change the default key bindings (or make them configurable)? `CTRL+T` is the currently the default visual studio "Code Search" key binding so it's not possible impossible to invoke this handy extension from the keyboard.

Thank you!

```xml
 <KeyBindings>
    <KeyBinding guid="guidDebugSingleThreadCmdSet" id="FocusOnCurrentThreadCmd" editor="guidVSStd97" mod1="Control" key1="t" mod2="Control" key2="t" />
    <KeyBinding guid="guidDebugSingleThreadCmdSet" id="SwitchToNextThreadCmd" editor="guidVSStd97" mod1="Control" key1="t" mod2="Control" key2="j" />
  </KeyBindings>
`

**Comment by mayerwin** [comment]
The key binding for the extension is actually CTRL+T+T (and CTRL+T+J), not just CTRL+T. Doesn't it work?

**Comment by gpshonik** [comment]
Right... soon as I type CTRL+T the code search window triggers so there's
no way to input the second part of the chord, unless I'm completely missing
something obvious.

**Comment by mayerwin** [comment]
OK, have you tried this to change either the Code Search shortcut, or the extension's shortcut:
https://learn.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2022

**Comment by gpshonik** [comment]
I would rather change the extension shortcut, but I can't seem to find it in the commands list, and the `CTRL+T+T` shortcut doesn't appear to be registered by anything.

**Comment by mayerwin** [comment]
I just tested and could not replicate the issue. I enabled Code Search (which is an experimental feature), restarted VS2022, and then CTRL+T doesn't do anything, it shows in the status bar: "CTRL + T was pressed. Waiting for second key of chord" (while CTRL+T+T still works). Maybe you can try uninstalling and reinstalling the extension. 
Also keep pressing CTRL to make sure it registers the chord. And you can try CTRL+T+CTRL+T.

**Comment by gpshonik** [comment]
Thanks for trying to repro. I just can't seem to get that combo to trigger. I'll make a custom VSIX with a different key binding to see if that works. Thanks again for making this extension. It's crazy that it's even needed.

**Comment by mayerwin** [comment]
OK! Maybe try disabling Code Search, and then enable again (in case it re-registers shortcut more as we expect).
